/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pngquant_LiqObject */

#ifndef _Included_org_pngquant_LiqObject
#define _Included_org_pngquant_LiqObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
