/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pngquant_PngQuant */

#ifndef _Included_org_pngquant_PngQuant
#define _Included_org_pngquant_PngQuant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pngquant_PngQuant
 * Method:    setMaxColors
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pngquant_PngQuant_setMaxColors
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_pngquant_PngQuant
 * Method:    setQuality
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pngquant_PngQuant_setQuality__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_pngquant_PngQuant
 * Method:    setQuality
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pngquant_PngQuant_setQuality__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_pngquant_PngQuant
 * Method:    setSpeed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pngquant_PngQuant_setSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_pngquant_PngQuant
 * Method:    setMinPosterization
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pngquant_PngQuant_setMinPosterization
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_pngquant_PngQuant
 * Method:    liq_attr_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_pngquant_PngQuant_liq_1attr_1create
  (JNIEnv *, jclass);

/*
 * Class:     org_pngquant_PngQuant
 * Method:    liq_attr_copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_pngquant_PngQuant_liq_1attr_1copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pngquant_PngQuant
 * Method:    liq_attr_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pngquant_PngQuant_liq_1attr_1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
